# Definición de la fuente reutilizable
fuente: &fuente "DejaVuSansM Nerd Font:pixelsize=26"

etiqueta_workspace: &etiqueta_workspace
  text: "{name}"
  font: *fuente
  margin: 13
  foreground: "d3c6aaff"
  on-click: "swaymsg --quiet workspace {name}"

ajustes_modulos_derecha: &ajustes_modulos_derecha
  margin: 12
  font: *fuente
  foreground: "d3c6aaff"

bar:
  height: 46
  location: top
  background: "333c43ff"
  left:
    - i3:
        sort: ascending
        strip-workspace-numbers: true
        content:
          "": 
            map:
              default:
                - string:
                    <<: *etiqueta_workspace
                    deco:
                      background:
                        color: "333c43ff"  # Fondo por defecto (onedark background)
              conditions:
                state == focused:
                  - string:
                      <<: *etiqueta_workspace
                      deco:
                        background:
                          color: "434f55ff"  # Fondo enfocado (visual_grey)
                state == urgent:
                  - string: 
                      <<: *etiqueta_workspace
                      deco:
                        background:
                          color: "e67e80ff"  # Rojo oscuro de onedark (dark_red)
  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{title}", font: *fuente, max: 110, foreground: "d3c6aaff"}

  right:
    - alsa:
        card: sysdefault:CARD=Generic
        mixer: Master
        content:
          map:
            conditions:
              muted:
                string:
                  text: "  {percent}%"
                  <<: *ajustes_modulos_derecha
                  deco:
                    background:
                      color: "e67e80ff"  # Rojo de onedark (red)
              ~muted:
                ramp:
                  tag: percent
                  min: 0
                  max: 100
                  items:
                    - string:
                        text: "  {percent}%"
                        <<: *ajustes_modulos_derecha
                    - string:
                        text: "  {percent}%"
                        <<: *ajustes_modulos_derecha
                    - string:
                        text: "  {percent}%"
                        <<: *ajustes_modulos_derecha
                    - string:
                        text: " {percent}%"
                        <<: *ajustes_modulos_derecha
    - clock:
        time-format: "%H:%M:%S"
        date-format: "%Y-%m-%d"
        content:
          string:
            text: "{date} {time}"
            <<: *ajustes_modulos_derecha
