# Editor por defecto
export EDITOR="vim"
export VISUAL="vim"

# Configuración de idioma y localización
export LANG="es_ES.UTF-8"
export LC_ALL="es_ES.UTF-8"

if test -z "${XDG_RUNTIME_DIR}"; then
  export XDG_RUNTIME_DIR=/tmp/"${UID}"-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi

# Iniciar sway en la primera terminal virtual si no está en Wayland
if [ -z "${WAYLAND_DISPLAY}" ] && [ "$(tty | grep -o '[0-9]*$')" -eq 1 ]; then
  echo "Iniciando sway..."
  exec dbus-run-session sway
fi
