# -------------------------
# Configuraciones de Entorno
# -------------------------
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export GTK_THEME=Adwaita:dark
export QT_QPA_PLATFORMTHEME=qt5ct
export MOZ_ENABLE_WAYLAND=1
export EDITOR=vim
export VISUAL=vim
export BROWSER=qutebrowser

if [ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  # Iniciar Sway
  exec sway
fi
