#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

# ejemplo instalación https://github.com/trapd00r/LS_COLORS
# en arch linux se puede instalar mediante aur "yay lscolors-git"
if [ -f "/usr/share/LS_COLORS/dircolors.sh" ]; then
    source /usr/share/LS_COLORS/dircolors.sh
fi

# Clonar como dice en la pagina git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1
# Para modificar tema ejecutar la funcion git_prompt_make_custom_theme
# explicado en el siguiente issue https://github.com/magicmonty/bash-git-prompt/issues/86
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=0
    GIT_PROMPT_THEME=Custom
    source $HOME/.bash-git-prompt/gitprompt.sh
else
    PS1='[\u@\h \W]\$ '
fi

export EDITOR="/usr/bin/vim"
export VISUAL="/usr/bin/vim"
